CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    ClientId UNIQUEIDENTIFIER NOT NULL,
    UserName VARCHAR(50) NOT NULL,
    DisplayName VARCHAR(50),
    Password BINARY(60) NOT NULL,
    IsAdmin INT DEFAULT 0,
    CONSTRAINT PK_Users PRIMARY KEY (Id, ClientId)
);